### ISSUE TITLE
Order of training D and G?

### ISSUE THREAD

**Issue by youngjung-obsolete** [LynnHo/CycleGAN-Tensorflow-Simple#1]
Hi, thanks for sharing nice and simple implementation.
Have you tried changing the order of training D and G?
i.e., currently you train G and Ds. How about training Ds first and then G?
To my sense, training G for randomly-initialized Ds is of no use.

**Comment by LynnHo** [comment]
@Youngjung I haven't tried Ds first beacuse I just follow the training order of the author's pytorch code https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix.

I think the training process is not sensitive to Ds or G first. As you say, training G for randomly-initialized Ds is of no use, but on the other hand, the first training of G can be viewed as a random weight initialization and it doesn't harm the training process.

Of course, it should have experiment.

**Comment by youngjung-obsolete** [comment]
Thanks. What a prompt and thorough reply!
FYI, I tried changing the order from XHUJOY's code and difference could not be found :)
