### ISSUE TITLE
Network model

### ISSUE THREAD

**Issue by qiuxiaqing** [LynnHo/CycleGAN-Tensorflow-Simple#10]
Dear sir:
     Thank you for the code you provided, I can already run it, but there are still some questions as following:
 1,The training effect is not very good, I trained epoch=6, looked at the results is not very good, I don't know if it is because the number of training is too small. what about yours?
2, I read the code you wrote, it is very good, and I have some points do not understand, such as the setting of some parameters, can you provide the model of the network? 
Thank you so much

**Comment by LynnHo** [comment]
@qiuxiaqing 
1. 6 epochs is not enough, besides, there is a related issue #5.
2. I am sorry that I haven't saved any model for this code.

**Comment by andrewginns** [comment]
@qiuxiaqing
1. The original paper recommends 200 epochs for training 

2. I have some saved models based on modifications of this code. Please find them here
 https://github.com/andrewginns/CycleGAN-Tensorflow-PyTorch/releases

The default parameters match those found in the orignal paper. What parameters would you like further information on?

**Comment by qiuxiaqing** [comment]
@andrewginns Thanks so much for your help. I will take a closer look at the model you provided. 
I have some small details in the code that I don't understand. For example,
1, In train.py, why set a2b_sample and b2a_sample,
2,In train.py, there is "g_loss_a2b = tf.losses.mean_squared_error(a2b_logit, tf.ones_like(a2b_logit))", I don't know why is tf.ones_like(...) instead of tf.zeros_like(...). 
The same is d_loss_a_real = tf.losses.mean_squared_error(a_logit, tf.ones_like(a_logit)). 
 I know that this is also the case in the original GAN network, but I don't know why it is, can you help me? 
My English is a bit poor, I don't know if you can understand me, thank you very much.
