### ISSUE TITLE
Generator loss starts around 2000 and never decreases

### ISSUE THREAD

**Issue by supre3th** [LynnHo/CycleGAN-Tensorflow-Simple#13]
i am working on Anomaly generation from Normal data.The dataset consists of 41 features ,all integers so i have padded the number 255  23 times to make it  8x8image.. discriminator loss keeps fluctuating ... even after 1000 iterations the Gloss is around 3000 range.

**Comment by LynnHo** [comment]
@supre3th I am sorry that I have no experience on your special task.

**Comment by supre3th** [comment]
thanks for the reply
