### ISSUE TITLE
It seems tensorflow-addons is no longer existing?

### ISSUE THREAD

**Issue by shi27feng** [LynnHo/CycleGAN-Tensorflow-Simple#14]
The error is below:
(base) xx:~/Workspace/CycleGAN-Tensorflow-2$ pip install tensorflow-addons
Collecting tensorflow-addons
  **Could not find a version that satisfies the requirement tensorflow-addons (from versions: )**
No matching distribution found for tensorflow-addons

**Comment by LynnHo** [comment]
@shi27feng you can refer to https://github.com/tensorflow/addons, tensorflow-addons requires tf2.

**Comment by Khoa-NT** [comment]
Hi @LynnHo 
Currently, tensorflow_addons hasn't supported windows yet.
Do you have any ideas to run without tensorflow_addons?

**Comment by LynnHo** [comment]
@shaolinkhoa I am sorry I have no idea about it. This project heavily depends on tensorflow_addons, because tensorflow_addons provides instance normalization which is not included in tensorflow. One solution is to implement the instance normalization by yourself but it takes times.

**Comment by jvmncs** [comment]
This could also happen if you attempt to install tensorflow-addons with python 3.7: https://github.com/tensorflow/addons/issues/75

**Comment by iszotic** [comment]
@shaolinkhoa, I use ROCm that doesn't support tensorflow addons so here's a variation without tensorflow-addons, I had to copy directly the instance normalization part from tensorflow addons repository, and it works https://github.com/iszotic/CycleGAN-Tensorflow-2
