### ISSUE TITLE
Image size in the dataset

### ISSUE THREAD

**Issue by civilServant-666** [LynnHo/CycleGAN-Tensorflow-Simple#20]
I noticed that images in the example dataset all have a square shape with 256*256 resolution. Does that mean I have to reshape my own images to the same image size when preparing my own dataset? 
PS: My images have a aspect of 1920:1080.

**Comment by LynnHo** [comment]
@civilServant-666 The code is for square images. An inelegant manner is to reshape your image before input and reshape it back after output. Otherwise you should modify the code to fit your data.

**Comment by civilServant-666** [comment]
I checked out the code. Seems like even if I input images with a rectangle shape, the "data.py" file will reshape the images to square images with the default 286*286 size and then crop them to 256*256 images. Please correct me if I am wrong.

**Comment by LynnHo** [comment]
@civilServant-666 Yes, you are right.
