### ISSUE TITLE
Environment setup

### ISSUE THREAD

**Issue by civilServant-666** [LynnHo/CycleGAN-Tensorflow-Simple#22]
As the tensorflow 2.0 has just been recently released and related libraries have been frequently updated, the prerequisites post in the readme might need to be further clarified. I came across several problems in setting up the environment in the past few days, which turned out to be caused by the compatibility between the libraries of different versions and the code.

So... To run the current code, the following versions of tensorflow-gpu and tensorflow-addons should be used.
Tensorflow 2.0 Alpha `pip install tensorflow-gpu==2.0.0-alpha0`
Tensorflow Addons 0.3.1 `pip install tensorflow-addons==0.3.1`

I have tried the following combinations, and they didn't work.
Tensorflow 2.0.0 + Tensorflow Addons 0.6.0
Tensorflow 2.0 Alpha + Tensorflow Addons 0.4.0 (or  >0.4.0)

For lower-level configuration, we need gcc, gpu driver, cuda and cudnn. For everyone' reference, I'll just put up my configuration here.
gcc 4.8.5
gpu GeForce GTX 1080 Ti (the driver should be compatible with the gpu, you can find and download it here https://www.nvidia.com/Download/index.aspx?lang=en-us )
cuda 10.0
cudnn 7.4.1

**Comment by andrewginns** [comment]
The reason the stable 2.0 branch doesn't work is likely because some of the fictions have been deprecated out renamed. The alpha branch probably has those fixings with deprecation warnings. Those problems will require a rewrite.

When it comes to an environment I'd recommend using anaconda and installing the tensorflow-gpu package, no need for cuda, cudnn and gcc. Though the problem with tf2.0 incompatibility isn't solved.

**Comment by LynnHo** [comment]
@civilServant-666 @andrewginns Thanks very much for pointing out the problem and giving suggestions.

I have no spare time to update the repo now, but I will update the code to tf 2.0.0 as soon as possible when I am free.

**Comment by civilServant-666** [comment]
@andrewginns , yes, exactly.  When I tried using tf2.0 to run the code, a warning popped up saying that a function related gpu does not exist. 

For the environment, could you kindly explain why there is no need for cuda etc. in the case of using anaconda? To my understanding, cuda etc. are must-have low-level libraries for using gpu acceleration.

**Comment by civilServant-666** [comment]
@LynnHo Thank you.

**Comment by andrewginns** [comment]
> @andrewginns , yes, exactly. When I tried using tf2.0 to run the code, a warning popped up saying that a function related gpu does not exist.
> 
> For the environment, could you kindly explain why there is no need for cuda etc. in the case of using anaconda? To my understanding, cuda etc. are must-have low-level libraries for using gpu acceleration.

Take a look at this https://www.pugetsystems.com/labs/hpc/Install-TensorFlow-2-beta1-GPU-on-Windows-10-and-Linux-with-Anaconda-Python-no-CUDA-install-needed-1520/

**Comment by civilServant-666** [comment]
@andrewginns Thanks

**Comment by LynnHo** [comment]
@civilServant-666 I have updated the code from TF2.0-alpha to TF2.0.
