### ISSUE TITLE
'len_dataset' is not defined in train.py

### ISSUE THREAD

**Issue by 48313758a** [LynnHo/CycleGAN-Tensorflow-Simple#26]
HI, I'm a green hand,I want to ask a question that why "'len_dataset' is not defined " was reported when I run the file 'train.py'. What the value of  len_dataset should be set?

**Comment by LynnHo** [comment]
> HI, I'm a green hand,I want to ask a question that why "'len_dataset' is not defined " was reported when I run the file 'train.py'. What the value of len_dataset should be set?

`len_dataset` need not be set. I haven't met this problem before. You can set a breakpoint after the first time the `len_dataset` appears, and see what happens.

**Comment by 48313758a** [comment]
Thank you for your reply ,i have solved the error.When i study your code, i delete some rows.
By the way ,will it be of efficiency if using the tf.keras to build the net directly like  the structure: keras.Mode().compile().....

**Comment by LynnHo** [comment]
> Thank you for your reply ,i have solved the error.When i study your code, i delete some rows.
> By the way ,will it be of efficiency if using the tf.keras to build the net directly like the structure: keras.Mode().compile().....

You can try it. In my perspective, it will be more efficient but not much.
