### ISSUE TITLE
the outputs is empty when I run test.py

### ISSUE THREAD

**Issue by lafayatte** [LynnHo/CycleGAN-Tensorflow-Simple#27]
the outputs is empty when I run test.py. The train.py is normal. And the datasets/monet2photo/<testA/testB> all have contents.And on error report.
the last traceback is
` 
 File "F:\python\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func   return func(*args, **kwargs)
  File "F:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "F:\python\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()`

**Comment by LynnHo** [comment]
@lafayatte I cannot figure out the problem from this information, and step by step debug may be needed.

**Comment by tong9999** [comment]
I am a beginner. Could you please give me a network structure diagram of the code (detailed to convolutional layer and normalized layer parameters)?Thankyou!

**Comment by Adamszk** [comment]
I have the same issue with test.py. But I am getting different error message:

` [*] Loading checkpoint...
 [*] No suitable checkpoint!
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    raise Exception('No checkpoint!')`

**Comment by LynnHo** [comment]
@Adamszk Did you fix the problem? Have you run train.py to obtain the checkpoint?

**Comment by Adamszk** [comment]
I am sure your code is fine.  Just a misplaced directory of the checkpoints.  I was just testing the code and decided to report any problems.  My computer is too old for this version of tensorflow.
