### ISSUE TITLE
a network structure diagram of the code 

### ISSUE THREAD

**Issue by tong9999** [LynnHo/CycleGAN-Tensorflow-Simple#28]
I am a beginner. Could you please give me a network structure diagram of the code (detailed to convolutional layer and normalized layer parameters)?Thankyou!

**Comment by LynnHo** [comment]
@tong9999 Sorry for the late response, please just refer to the CycleGAN paper for the network architecture, or there is a clear architecture definition in [model.py](https://github.com/LynnHo/CycleGAN-Tensorflow-2/blob/master/module.py).
