### ISSUE TITLE
Using the wgan configuration gives bad results

### ISSUE THREAD

**Issue by OriYitzhaki** [LynnHo/CycleGAN-Tensorflow-Simple#30]
Hi,
I've tried to train the model with the "wgan" options turned on, and got pretty bad results.
for example (iter 240000):
![iter-000240000](https://user-images.githubusercontent.com/28001669/89407844-2bb27200-d728-11ea-80da-991a9e0049fb.jpg)

I can see a grid-like on the first translation (the cycled image looks fine) but I'm not sure what causing it.
the grid is present on every result (excluding the very begining).

the command I'm using:
`python3 train.py --output=output_wgan --adversarial_loss_mode=wgan --gradient_penalty_mode=wgan-gp
`
I wonder if I should change some of the weights for better results, and if so to which value?

**Comment by LynnHo** [comment]
@OriYitzhaki Try to train D 5 times since WGAN need more D training. I.e., change this line
https://github.com/LynnHo/CycleGAN-Tensorflow-2/blob/088263857d2fb9b8f06caa281b62bcad43eddadc/train.py#L149
to be
```python
for _ in range(5):
	D_loss_dict = train_D(A, B, A2B, B2A)
```

**Comment by OriYitzhaki** [comment]
> @OriYitzhaki Try to train D 5 times since WGAN need more D training. I.e., change this line
> https://github.com/LynnHo/CycleGAN-Tensorflow-2/blob/088263857d2fb9b8f06caa281b62bcad43eddadc/train.py#L149
> 
> 
> to be
> ```python
> for _ in range(5):
> 	D_loss_dict = train_D(A, B, A2B, B2A)
> ```

An Update for whoever will read the thread:
at the moment that mentaioned addition solely does not seems to work. 
the generator's activations seems to be too strong and around the mid of epoch 51, the pixel values are `nan`

**Comment by LynnHo** [comment]
@OriYitzhaki I will try to figure out the problem. It seems that there are some bugs in WGAN-GP with TF2.

**Comment by samdubuis** [comment]
While running your train.py --dataset myowndataset, I always get an error :

Traceback (most recent call last):
  File "train.py", line 208, in <module>
    tl.summary(G_loss_dict, step=G_optimizer.iterations, name='G_losses')
  File "/ivrldata1/students/sdubuis/semester_project_MA/code/CycleGAN-Tensorflow-2/tf2lib/utils/utils.py", line 64, in summary
    _summary(name, data)
  File "/ivrldata1/students/sdubuis/semester_project_MA/code/CycleGAN-Tensorflow-2/tf2lib/utils/utils.py", line 47, in _summary
    tf.summary.scalar(name, data, step=step)
AttributeError: module 'tensorflow._api.v2.summary' has no attribute 'scalar'

Would you have an idea why and how to correct it ?
Best regards, 
Samuel
