### ISSUE TITLE
AssertionError running train.py

### ISSUE THREAD

**Issue by ojc970117** [LynnHo/CycleGAN-Tensorflow-Simple#31]
AssertionError: `images` should be in the range of [-1.0,1.0]!

What is this mean??

work is stop at 100th Inner Epoch Loop with that error message
I changed nothing just run with your modules
help me plz

**Comment by LynnHo** [comment]
@ojc970117 What type of your data is?

**Comment by ojc970117** [comment]
<tf.Tensor 'input_4:0' shape=(None, 256, 256, 3) dtype=float32>

this is my input datatype
i was testing horse2zebra datasets

**Comment by LynnHo** [comment]
@ojc970117 I have tested the code and everything works. The code is updated to TF2.2, and you can just follow the newest README file to create the proper environment.

**Comment by OriYitzhaki** [comment]
> <tf.Tensor 'input_4:0' shape=(None, 256, 256, 3) dtype=float32>
> 
> this is my input datatype
> i was testing horse2zebra datasets

Happened to me too when I've tried the code with the wgan-gp option on.
The activaions are too strong and the image values are `nan` (which is not in the range of +-1).

**Comment by LynnHo** [comment]
@OriYitzhaki WGAN-GP with this code doesn't work, I guess WGAN-GP is not suitable for this architecture.
