### ISSUE TITLE
What do the samples mean?

### ISSUE THREAD

**Issue by George-Ogden** [LynnHo/CycleGAN-Tensorflow-Simple#35]
This is more of a question than an issue, but what do the samples mean that are generated during training? I would be really grateful if someone could explain, please

**Comment by philthestone** [comment]
This helps you understand how well the network is perfoming: 
What you can see are the two cycles: A --> B --> A and B --> A --> B
So on the top row the first image is an image from category A. Then the middle picture in the top row is the same image translated into category B. And finally the last image in the top row is another translation back into category A. 

The bottom row is the same but starting with an image from category B.

**Comment by George-Ogden** [comment]
That makes sense, thanks
