### ISSUE TITLE
How to Resume Training From checkpoint

### ISSUE THREAD

**Issue by snow1929** [LynnHo/CycleGAN-Tensorflow-Simple#38]
Hi,
I see the code in train.py
![image](https://user-images.githubusercontent.com/42559501/130165949-39d99478-7a47-4f64-b616-8d0aac03e6e1.png)
But I am not sure whether the training would resume from the latest checkpoint.
Does it resume from the latest checkpoint?

**Comment by LynnHo** [comment]
> Hi,
> I see the code in train.py
> ![image](https://user-images.githubusercontent.com/42559501/130165949-39d99478-7a47-4f64-b616-8d0aac03e6e1.png)
> But I am not sure whether the training would resume from the latest checkpoint.
> Does it resume from the latest checkpoint?

@syue-fen Yes, the latest one.
