### ISSUE TITLE
No training progress?

### ISSUE THREAD

**Issue by victor-felicitas** [LynnHo/CycleGAN-Tensorflow-Simple#4]
Hello, thanks for the great job!

It is the only TF implementation that works on Hiptensorflow and ROCm without problems.

However, I have observed that during training there is no progress...
After 9 epochs images in sample_images folder are not recognisable at all.

![image](https://user-images.githubusercontent.com/36967768/37564677-bf1a4d00-2aab-11e8-8f8e-a5dc65060d19.png)

Everything looks pixelated and unrecognizable... And 0 epoch pictures actually look better (shapes can be seen)

Is it ok after 9 epochs?

**Comment by LynnHo** [comment]
@victor-felicitas I haven't seen this phenomenon, but I only use tf1.0 for experiments. I will test a newer version of tf. I will tell you the result after the experiments.

**Comment by LynnHo** [comment]
@victor-felicitas I have tested the code on tf1.6, the result is fine and I haven't met this strange phenomenon. Do you change some hyper-parameters?
