### ISSUE TITLE
conversion is not proper

### ISSUE THREAD

**Issue by chandakQ** [LynnHo/CycleGAN-Tensorflow-Simple#8]
I have attached one of the images from "sample_images_while_training" folder
![selection_032](https://user-images.githubusercontent.com/39828486/42033362-4b12c49c-7afa-11e8-8896-8d6ccbf76f65.png)
This image is after 48 epochs
where right image = input
the middle = orange if the input is apple or vice-versa
right = reconstructed image of the input image

The problem I am facing: In the first row, middle image(orange) has got stalk, which it should not. Also, in the second row, the texture of both apple and orange looks same.

Could you please suggest me any solution to these problems.

**Comment by LynnHo** [comment]
@chandakQ I haven't solved the problem, it seems to be the problem of CycleGAN itself: the color is easily transferred but the shape and the texture are kept.

**Comment by chandakQ** [comment]
@LynnHo  What, according to you, could be a possible solution. What changes should I make or is there any better GAN architecture I could use for this use case?

**Comment by LynnHo** [comment]
@chandakQ You can try to use a global discriminator instead of a patch discriminator and reduce the weight of the cycle consistency loss. And I suggest you to read this paper https://arxiv.org/abs/1708.00315.

**Comment by chandakQ** [comment]
Thank you @LynnHo for the suggestions, because of which the texture adaption issue has been resolved.

There are still a few things about the result which are not plausible:
1) In apple-to-orange, the shape of the generated orange is same as that of the apple in the input image. In reality, it is not.
![shape](https://user-images.githubusercontent.com/39828486/42170524-6e07bdda-7e34-11e8-93b6-fec1a8b2e256.png)



2) The background gets changed completely.
![background_img1](https://user-images.githubusercontent.com/39828486/42170546-7d9f1f4a-7e34-11e8-861a-009832bb6de6.png)
![background_img2](https://user-images.githubusercontent.com/39828486/42170548-7dd81da4-7e34-11e8-9910-9e85c2107c02.png)





Could you please suggest some solution to both the problems.

Thanks!!

**Comment by LynnHo** [comment]
@chandakQ I haven't got an idea to sovle the shape problem of CycleGAN. As for the background problem, this #5 may help.
